language: crystal

crystal:
  - latest
  - nightly

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libasound-dev
  - sudo apt-get install -y libjack-dev
  - (cd dep && crystal run build.cr)
